jobs:
- job: x64
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      arch: x64

- job: armhf
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      qemu: 'true'
      arch: armhf

- job: arm64
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      qemu: 'true'
      arch: arm64

- job: alpine
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      arch: alpine

- job: stretch_arm64
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      arch: stretch-arm64

- job: stretch_armhf
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      arch: stretch-armhf

- job: buster_arm64
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      arch: buster-arm64

- job: buster_armhf
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      arch: buster-armhf