jobs:
- job: x64
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      arch: x64

- job: ia32
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      arch: ia32

- job: armhf
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      qemu: 'true'
      arch: armhf

- job: alpine
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build.yml
    parameters:
      arch: alpine
