jobs:
- job: x64
  pool:
    vmImage: 'Ubuntu-16.04'
  parameters:
    arch: x64
  steps:
  - template: build.yml

- job: ia32
  pool:
    vmImage: 'Ubuntu-16.04'
  parameters:
    arch: ia32
  steps:
  - template: build.yml

- job: armhf
  pool:
    vmImage: 'Ubuntu-16.04'
  parameters:
    arch: armhf
    qemu: 'true'
  steps:
  - template: build.yml
