steps:
- ${{ if eq(parameters.qemu, 'true') }}:
  - script: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    displayName: 'Register Docker QEMU'
- task: Docker@2
  displayName: 'Build and Push Container Image'
  inputs:
    containerRegistry: VSCodeHub
    repository: 'vscode-linux-build-agent'
    Dockerfile: ${{ parameters.arch }}/Dockerfile
    buildContext: ${{ parameters.arch }}
    tags: ${{ parameters.arch }}
