steps:
- task: Docker@2
  displayName: 'Build and Push Container Image'
  inputs:
    containerRegistry: VSCodeHub
    repository: 'vscode-linux-build-agent'
    Dockerfile: $(ARCH)/Dockerfile
    buildContext: $(ARCH)
    tags: $(ARCH)
